### ISSUE TITLE
Error 502 after configuring standard auth

### ISSUE THREAD

**Issue by artybdrlt** [YunoHost-Apps/bookstack_ynh#115]
### Describe the bug

Hello,
I just installed a fresh bookstack instance (version 23.2.3~ynh2) and as soon as I changed the authentication setting from LDAP to standard I get an error 502. Even though I try to go back to the LDAP auth, I still get this error. Rebooting the service doesn't change anything.

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 11.1.17 
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no

### Expected behavior

I should be able to log in with standard authentication.

**Comment by ericgaspar** [comment]
Do you have logs output from Bookstack service?

**Comment by ericgaspar** [comment]
should be fixed
