### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/bookstack_ynh#12]
Here are the logs:

https://paste.yunohost.org/raw/takezizulo

Tried to update by web

**Comment by MX10-AC2N** [comment]
Hello, I also encounter a problem to carry out the last update. On my rk3328 box this completely "freezes" the system, forced to unplug ...

**Comment by brimwats** [comment]
> Hello, I also encounter a problem to carry out the last update. On my rk3328 box this completely "freezes" the system, forced to unplug ...

I had to uninstall and reinstall and all works good now.
