### ISSUE TITLE
401 error after changing YNH admin password.

### ISSUE THREAD

**Issue by KnightNine** [YunoHost-Apps/bookstack_ynh#121]
### Describe the bug

I was changing the password to my admin account to something more secure and then tried to use bookstack which directed me to a `401 Authorization Required` error. I have all my documentation on there so I can't uninstall and re-install.
I tried updating Bookstack from `23.02.2~ynh2` (i think) to `23.05.2~ynh2` to see if that would fix it but to no avail.
Hopefully bookstack eventually forgets my credentials and takes me to a login page, but if not, how would I fix this?

![Capture](https://github.com/YunoHost-Apps/bookstack_ynh/assets/34152090/df760da8-98e0-4080-a412-7b4d79deb435)

### Context

- Hardware:  Old laptop 
- YunoHost version: 11.1.20
- I have access to my server: yes to all
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch:  23.05.2~ynh2

### Steps to reproduce

1) login to bookstack
2) change your admin account password through the webadmin's  `/yunohost/admin/#/users` page (in my case this is the only account)
3) go back to the bookstack app and receive the error.
4) experience frustration.

I'm not sure how to do this:
- *If you used the webadmin, please perform the equivalent command from the CLI first.* 

### Expected behavior

I suppose Bookstack should log me out and take me to the login page if my "credentials are invalid".

### Logs

changed credentials:
https://paste.yunohost.org/raw/upoyivupow
then this which I presume was an auto backup:
https://paste.yunohost.org/raw/kesovezego
then updated bookstack:
https://paste.yunohost.org/raw/yaguqoqepa

**Comment by KnightNine** [comment]
tried using a different device to use bookstack and it gives the same error, this is not client side.

**Comment by KnightNine** [comment]
Changing my password back to what it was fixes the issue, but I can't change my password then...☹

**Comment by KnightNine** [comment]
> LDAP authentication

@ericgaspar probably not, is that a setting or something within the ynh webadmin or in bookstack?

**Comment by ericgaspar** [comment]
Bookstack has two Authentication systems
Standard : with email and password
LDAP : your YunoHost admin name and pwd

**Comment by KnightNine** [comment]
@ericgaspar I guess so then since I need to login to ynh before logging in to bookstack.

**Comment by KnightNine** [comment]
it eventually fixed itself after leaving it for a day...
