### ISSUE TITLE
SMTP configuration

### ISSUE THREAD

**Issue by bidroidk** [YunoHost-Apps/bookstack_ynh#138]
### Describe the bug

SMTP is not working. Trying  to send an email test from the "maintenance" page is failed

### Context

- Hardware: My own computer
- YunoHost version: 11.2.4
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  no

### Steps to reproduce

Send a email test

### Expected behavior

Sending email is successfull

### Logs

Two kind of errors : 
- In .env file if MAIL_HOST is set to "localhost", there is an error concerning certificate verification on the CN attribute
- In .env file MAIL_USERNAME is set to "bookstack" AND if the setting above is fixed, there is an authentication error.

So, I guess the to setting above must be modified : 
* MAIL_HOST to the server fqdn
* MAIL_USERNAME must be set to "null" instead of bookstack.

Hope this help

Many thanks for your job about bookstack

-- 
Bidroidk

**Comment by ericgaspar** [comment]
#140 should fix the issue
