### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/bookstack_ynh#43]
### Describe the bug

I cannot log into my newly installed BookStack instance. First of all, nowhere in the documentation I can find any hint concerning what the login email and password should be. Nevertheless, I attempted logging in with the YunoHost user password and several different emails:

- `username@application.tld`
- `username@server.tld`
- `username` only

I have no success.

Even by clicking on “reset password” I try any of those email addresses and I receive no reset email.

<br>

### Context

**Hardware:** VPS bought online
**YunoHost version:**  4.3.6
**I have access to my server :** Through SSH
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no

<br>

### Steps to reproduce

- Installed the app successfully
- tried to log in

<br>

### Expected behavior

*Successfully logging in*.

<br>

### Logs

/

**Comment by alexAubin** [comment]
[The README seems to mention](https://github.com/YunoHost-Apps/bookstack_ynh#disclaimers--important-information) : 

>For the first time Login, use the default credentials admin@admin.com and password. You should change these details immediately after logging in for the first time.

**Comment by xplosionmind** [comment]
I missed this! I am sorry. Thanks a lot!
