### ISSUE TITLE
Switching domain names breaks the instance

### ISSUE THREAD

**Issue by daalta** [YunoHost-Apps/bookstack_ynh#44]
### Describe the bug

Switching domain names through the YUnoHost UI can lead to the following error:

```
An Error Occurred
An unknown error occurred
```
This renders bookstack unusable.

### Context

- Hardware: Hetzner Cloud VPS
- YunoHost version: 4.3.6.2 
- I have access to my server: Through SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 21.05.3~ynh1

### Steps to reproduce

1. Set up up working bookstack instance & fill it with content
2. Add a new, properly configured domain name to YunoHost
3. Switch BookStack to that new domain name

### Expected behavior

Bookstack should continue to work, although it might exhibit some broken URLs. The BookStack docs recommends the following command to fix broken links, though they do not describe whether this applies to broken instances as well.

```php
# Searches for <oldUrl> and replaces it with <newUrl>
php artisan bookstack:update-url <oldUrl> <newUrl>

# Example:
php artisan bookstack:update-url http://docs.example.com https://demo.bookstackapp.com
```

### Logs

I would require assistance retrieving the logs.

**Comment by daalta** [comment]
I have identified two issues.
- The `APP_KEY` in `.env` gets reset when switching domains.
- `APP_DEBUG` completely disappears from `.env`.

After fixing my `APP_KEY` and running `php artisan bookstack:update-url <oldUrl> <newUrl>` my instance works again!

**Comment by ericgaspar** [comment]
@daalta Thanks for the help.
This is partially fixed in testing https://github.com/YunoHost-Apps/bookstack_ynh/pull/38 but we still have a problem with the images not showing after the URL change 🤔

**Comment by daalta** [comment]
Great to hear!

Hmmm well I was able to fix it by running the the artisan command from my previous comment. I'd almost call it expected behaviour, judging from their troubleshooting guide.

**Comment by ericgaspar** [comment]
I made some progress. We can now change the URL one time without breaking the image link.
so old_url -> new_url works but changing again breaks image link.

**Comment by ericgaspar** [comment]
#38 Should partially resolve the problem... There is still issues with subdomain change_url

**Comment by ericgaspar** [comment]
@daalta I am about to merge this fix. It will be appreciated if you can test it to confirm it works.
```
sudo yunohost app install https://github.com/YunoHost-Apps/bookstack_ynh/tree/Fix-url
```

**Comment by ericgaspar** [comment]
closing with #38
