### ISSUE TITLE
Updates clear certain .env files

### ISSUE THREAD

**Issue by daalta** [YunoHost-Apps/bookstack_ynh#67]
Certain `.env` values get overwritten when updating.
```
APP_KEY
MAIL_FROM_NAME
MAIL_FROM
APP_DEFAULT_DARK_MODE
```
Auth methods are also removed, for services like Google and Discord.

**Comment by ericgaspar** [comment]
That is expected. The config is being regenerated so that everyone gets the updated configuration. The next version should keep the `.env` file.

**Comment by daalta** [comment]
Thank you for clarifying, Eric!

**Comment by ericgaspar** [comment]
And of course, the next update will overwritt the `.env` file 😁
