### ISSUE TITLE
installation process don't finish: do not run composer as root/sudo

### ISSUE THREAD

**Issue by diony44** [YunoHost-Apps/bookstack_ynh#7]
YNH 4.1.6 with Debian 10

I run the command for installing BookStack in the CLI. It gives me this warning and don't continue.
`Warning: Do not run Composer as root/super user! See https://getcomposer.org/root for details`

I set up a new non root/non sudo user and tried to start the installation using the new user. When I run the command with sudo it says 'user has no sudo priviliges' and when I try without sudo the installation don't start because the command yunohost needs to be run with sudo.

I already asked on reddit an one user suggested that BookStack made slight changes to the install script and that the yunohost package might need to be updated too. [https://github.com/BookStackApp/devops/commit/d72f29bb83773e0882781afa9f5d209be7c92beb](url)

Could this be the problem? Or what else could be the problem?

**Comment by ericgaspar** [comment]
The app has been repackaged. I still have issues with upgrade script...
Can you try to install with testing?
`sudo yunohost app install https://github.com/YunoHost-Apps/bookstack_ynh/tree/testing`

**Comment by ericgaspar** [comment]
sould be fixed with #8
