### ISSUE TITLE
Custom .env changes are gone

### ISSUE THREAD

**Issue by memo-567** [YunoHost-Apps/bookstack_ynh#74]
After update to `22.06~ynh1` all custom changes in `.env`  file, like custom theme folder or custom session time, are gone.

**Comment by ericgaspar** [comment]
Yes there are... We need to repopulate the `.env` file so we get the new variables... previous configuration must have been saved (I can't remember where...)

**Comment by memo-567** [comment]
Ah, okay.

I also can't add book tags after update to BookStack v22.06 anymore.

But I think, this is a bookstack issue, and  therefore I posted an issue there.

https://github.com/BookStackApp/BookStack/issues/3527

**Comment by ericgaspar** [comment]
Also, don't forget to mention that BoockStack as been install thought YunoHost script.

**Comment by ericgaspar** [comment]
There is a `Book tags` section in the `Edit Book` page... Is it not what you are looking for?
![Capture d’écran 11](https://user-images.githubusercontent.com/46165813/175772848-71ee5111-c1b3-409c-8d77-eab0b40ec1a7.png)

**Comment by memo-567** [comment]
That's it, but changes / additions are not saved to database after update.

Reverting to `BookStack v22.04.2 `and everything works fine again.

**Comment by memo-567** [comment]
Fixed in BookStack v22.06.1 

https://github.com/BookStackApp/BookStack/releases/tag/v22.06.1
